import { Post } from "src/app/interfaces/post.interface";


export const POSTS: Post[] = [
    {
        id: 1,
        titulo: 'Eco-friendly camping tips for staycations',
        subtitulo: "Ten top tips for an eco-friendly camping trip:",
        texto: "1. Use, reuse and recycleHabits, like recycling, are usually followed at home but are quick to disappear when we go on holiday.However, it’s important to keep up good environmental habits during a camping trip too.Sort rubbish into recyclable and non- recyclable bags and instead of buying single - use cutlery, plates, and washcloths for the trip, bring ones from home that are less treasured. 2. Don’t be rubbishWhen out in the wild, it is important to be mindful of where you are.Even the smallest bit of waste can do a lot of damage to the environment and local wildlife.Take biodegradable bin bags when you’re out and about, to carry around unwanted rubbish.When camping, leave rubbish somewhere safe and out of reach of wildlife.Dispose of your rubbish in designated bins and close the lid to stop animals from getting in and eating anything potentially harmful. 3. Check for chemicals The products used during a camping trip can have even more of an impact on nature than leaving rubbish behind! Many household products, such as moisturiser, toothpaste, sunscreen, and insect repellent, contain chemicals that may pollute the environment they are used in.Plan ahead and pick sustainable, all - natural products. 4. Go solar Gadgets are needed in every aspect of life and whilst the idea of forgoing technology during a camping trip might be nice, sometimes gadgets are needed.However, it is easy to make environmentally friendly choices when charging and using these products.Solar technology has advanced a long way and is a great alternative energy supply for almost all electrical appliances.It will require a bit of forward planning and a small investment in solar - powered alternatives. 5. Refill water Instead of taking a multi - pack of single - use water bottles, reduce plastic waste by finding a safe source of water and packing reusable water butts, boxes, or bottles.Doing this for the duration of the trip will create a big reduction in the amount of waste created whilst camping and reduce the amount of plastic waste ending up in landfills. 6. Equipment First - time campers with no gear should think twice before picking up their equipment.Tents made of plastic will eventually end up in landfill, so first - time buyers should opt for one made from natural materials like cotton, hemp, or even recycled water bottles.Camping gear can be expensive, so also consider the benefits of buying second - hand tents, mats and air mattresses. 7. Stay sustainable Getting good grub when hiking, walking and exploring is important when camping.Before doing the big shop ahead of camping, look at greener and more sustainable options.Invest in outside food storage solutions and minimise waste created by food packaging, by cooking from fresh.Shopping local will also reduce campers carbon footprints, as the food will have to travel fewer miles. 8. Getting there Camping hotspots are quick to fill up, particularly in high season, so it is worth considering the environmental impact of having lots of people in natural spaces at once.Whilst stunning campsites along the coast might be appealing, put some thought into the emissions produced from the petrol used to get there.9.  While there When camping in the wild, and not at a dedicated campsite, it is important to pick a spot that isn’t home to animals - somewhere you can see someone has camped before would be ideal.Avoid moving or damaging vegetation to pitch your tent and consider the local wildlife in the area.10.  Be prepared Before heading out of the door, double - check and make sure everything needed for the camping trip is packed.Being overly prepared can reduce waste, as campers won’t need to rush out to make unnecessary purchases that could have been brought from home.Only having to make one trip to the campsite will also reduce air pollution.",
        autor: 'Jesica Cepero',
        imagen: 'https://www.traveldailynews.com/assets/thumbnails/2c/2ca0d3cbf447a7c1e46732c4844f0e9e.jpg',
        fecha: '17/05/2021',
        categoria: 'Travel',
    },
    {
        id: 2,
        titulo: 'Best foldable phones 2021',
        subtitulo: 'As smartphone tech seeks new solutions, the foldable smartphone became an inevitable answer.',
        texto: "There were numerous hurdles, but the foldable phones did make it to markets in late 2019. Samsung managed to retail more than 400,000 units of the 1st-gen Galaxy Fold in spite of the exorbitant price. It then marched ahead with a few more design updates and variations. Herein you will gain the details of all other folding phones from various other brands. Judging by the enthusiasm towards this new phone form factor, we are optimistic that the trend will slowly but steadily catch on.That brings us to the question —        How’s the software ecosystem optimized for foldables ?            Android has built-in ‘Screen Continuity’ support, and so developers won’t have to go through an awful lot of trouble to optimize their apps for foldable displays.Simply put, it’s the feature by which an app could smoothly and seamlessly transform to and fro the different screen sizes.",
        autor: 'Jesica Cepero',
        imagen: 'https://cdn.pocket-lint.com/r/s/1200x/assets/images/148375-phones-feature-foldable-phones-image1-158skhnyrl.jpg',
        fecha: '21/04/2021',
        categoria: 'Technology',
    },

    {
        id: 3,
        titulo: 'The importance of yoga in our daily life',
        subtitulo: 'Yoga is not a religion, it is a way of living ',
        texto: "The art of practicing yoga helps in controlling an individual’s mind, body and soul. It brings together physical and mental disciplines to achieve a peaceful body and mind; it helps manage stress and anxiety and keeps you relaxing. It also helps in increasing flexibility, muscle strength and body tone. It improves respiration, energy and vitality. Practicing yoga might seem like just stretching, but it can do much more for your body from the way you feel, look and move.Yoga asanas build strength, flexibility and confidence.Regular practice of yoga can help lose weight, relieve stress, improve immunity and maintain a healthier lifestyle.",
        autor: 'Jesica Cepero',
        imagen: 'https://diariamenteali.com/medias/conoce-los-tipos-de-yoga-y-encuentra-el-ideal-para-ti-1900Wx500H?context=bWFzdGVyfGltYWdlc3wxMDYyMjl8aW1hZ2UvanBlZ3xoMjIvaDFjLzkwNzQ0MjYwODU0MDYvY29ub2NlLWxvcy10aXBvcy1kZS15b2dhLXktZW5jdWVudHJhLWVsLWlkZWFsLXBhcmEtdGlfMTkwMFd4NTAwSHw1ZjBkYjViMTI4NzFkOTU4NDg3NGI1M2UzOGJmOTUyOTg5MTgxYTI4ZjUzNDhhNTc4ZGZlNWRiMGI2Zjc4OTU1',
        fecha: '02/03/2021',
        categoria: 'Health',
    },
    {
        id: 4,
        titulo: 'Extraordinary Glass Objects',
        subtitulo: 'Researchers in France develop a technique that doesn’t use a layer-by-layer additive manufacturing method.',
        texto: "he French team’s approach is different in that unlike stereolithography, which builds up an object layer by layer, the new process uses a different technique that gives it more flexibility, said research team leader Laurent Gallais from the Fresnel Institute. “Our new process avoids the limitations of these processes by using a laser beam to transform--or polymerize--a liquid precursor into solid glass, ” he said in a press statement. They include the speed of the printing process, which is limited by the time it takes to build each layer, Gallais noted.This means it can be difficult to create layers with consistent thicknesses when using highly viscous resins, requiring the use of carefully positioned supports that are removed once the object hardens when printing complex objects, researchers noted. The team created its laser - based process using multiphoton polymerization, which links liquid monomer molecules together into a solid polymer only at the precise laser focal point, researchers said.They then use another process to turn the polymer object into glass. This technique allows for direct fabrication of 3D parts ranging in size from a few microns to tens of centimeters with a resolution capable by the optics used to shape objects using lasers, Gallais said. “Glass is one of the primary materials used to make optics, ” he said in a press statement.“Our work represents a first step toward developing a process that could one day allow scientists to 3D - print the optical components they need.” Overcoming Challenges Developing the process was not without its challenges, however, researchers said. 3D - printing glass objects require a material that is transparent at the wavelength of the laser both during its initial liquid phase and once polymerization is complete.The material also must be capable of absorbing the laser light at half the laser wavelength to initiate the multiphoton polymerization process. To accomplish the results they were seeking, the team combined a photochemical initiator to absorb the laser light, a resin, and a high concentration of silica nanoparticles in the material with which they used to print the polymer object.The result was a material that was well - suited to the laser as well as could produce an object without deformation or the use of supports due to its high viscosity, researchers noted. To test their material and process, the team first validated that a solid object could be created using silica nanoparticle mixtures.They then printed several complex shapes using the material, after which they transformed the polymerized parts into glass. Researchers produced a variety of silica glass objects, such as miniature models of a bike and the Eiffel Tower without any pores or cracks, using their process. “Our approach could potentially be used to produce almost any type of 3D glass object, ” Gallais observed in a press statement.“For example, we are exploring the possibility of producing glass parts that could be used on luxury watches or perfume bottles.”",
        autor: 'Jesica Cepero',
        imagen: 'https://www.designnews.com/sites/designnews.com/files/styles/article_featured_retina/public/AdobeStock_59665824.jpg?itok=uJF9EjWt',
        fecha: '02/03/2021',
        categoria: 'Design',
    },
    {
        id: 5,
        titulo: "Tokyo Olympics: Why doesn't Japan cancel the Games?",
        subtitulo: 'The Tokyo Olympics are now just over two months away',
        texto: "The situation is not looking great in Japan. A coronavirus state of emergency has been extended in the capital Tokyo and three other major prefectures as cases continue to rise. Yet there's been no word about cancelling the Games, despite both health experts and public opinion being stacked against them. Current polls in Japan show nearly 70% of the population do not want the Olympics to go ahead, but the International Olympic Committee(IOC) remains steadfast that the spectacle will take place. Japan has long insisted there was no question the Olympics, which should have taken place last summer, would be held and will be safe. Yet earlier this week, Prime Minister Yoshihide Suga for the first time appeared to bow to the pressure of public opinion, saying that the government would 'not put the Olympics first' - but adding that ultimately, the decision would lie with the IOC.",
        autor: 'Jesica Cepero',
        imagen: 'https://acf.geeknetic.es/imgw/imagenes/noticias/2019/16343-jjoo-esports-1.jpg?f=webp',
        fecha: '02/03/2021',
        categoria: 'Culture',
    },
    {
        id: 6,
        titulo: 'SoftBank Sells Renewable-Energy Unit in India',
        subtitulo: 'SoftBank Group Corp. is selling at $3.5 billion',
        texto: "SoftBank Group Corp. is selling its Delhi-based renewable-energy unit to an Indian rival, a step that effectively pulls the plug on what was once the world’s most ambitious solar investor.Adani Green Energy Ltd.said Wednesday it was buying SB Energy India in a deal that values the unit at $3.5 billion, an amount it said would be India’s largest renewable- energy transaction.The unit has nearly five gigawatts of renewable - power assets in India—mostly solar power—and is 80 % owned by SoftBank, with the remaining stake held by Indian conglomerate and longtime SoftBank partner Bharti Group.Adani didn’t say how much it was paying. The deal involves the unit of SoftBank that had been responsible for the company’s most aggressive solar investments and plans, including a proposed $200 billion, 200 gigawatt project in Saudi Arabia that was announced with great fanfare by SoftBank Chief Executive Masayoshi Son and Saudi Crown Prince Mohammed bin Salman in 2018. That project was later shelved as competition for solar projects rose and returns on plants dropped.",
        autor: 'Jesica Cepero',
        imagen: 'https://s03.s3c.es/imag/_v0/770x420/1/b/e/700x420_softbank-coronavirus.jpg',
        fecha: '02/03/2021',
        categoria: 'Business',
    },


    {
        id: 7,
        titulo: 'Science drill ship sets depth record off Japan',
        subtitulo: 'A new deep-ocean record has been set for a scientific drilling operation.',
        texto: "Researchers working off the coast of Japan lowered a giant piston corer through more than 8km of water in order to pull sediments from the seabed. It took two hours and 40 minutes simply for the equipment to descend into position above the ocean floor. The drilling exercise, mounted from the Research Vessel Kaimei, is part of a project to read the history of great earthquakes in the region. The chosen core site in the Japan Trench is very close to the epicentre of the Magnitude 9.1, Tohoku- oki event in 2011, which also produced a tsunami that devastated communities on the nation's eastern seaboard, and knocked out the Fukushima nuclear plant. The 37m of sediment retrieved by the piston corer will hopefully preserve details of much older quakes - those that occurred before any written accounts",
        autor: 'Jesica Cepero',
        imagen: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/527D/production/_118571112_kaimei04-1.jpg',
        fecha: '02/03/2021',
        categoria: 'Science',
    },
    {
        id: 8,
        titulo: 'Bitcoin',
        subtitulo: 'The price of Bitcoin fell for the first time in three months, after China imposed fresh curbs on crypto-currencies.',
        texto: "Beijing banned banks and payment firms from providing services related to crypto-currency transactions.  It also warned investors against speculative crypto trading on Tuesday. It follows falls in Bitcoin of more than 10% last week after Tesla said it would no longer accept the currency.On Wednesday afternoon, Bitcoin recovered some ground, although it was still down - 10.4 % at $38, 131. Meanwhile, other digital currencies such as Ether, which acts as the fuel for the Ethereum blockchain network, and Dogecoin lost as much as 22 % and 24 % respectively.",
        autor: 'Jesica Cepero',
        imagen: 'https://ichef.bbci.co.uk/live-experience/cps/624/cpsprodpb/53F8/production/_118569412_bitcoin2.jpg',
        fecha: '02/03/2021',
        categoria: 'World',
    },
]
